#!/bin/sh

for s in secure insecure; do
	for dt in deleg-only ns-only both; do
		echo "### Testing $dt $s"
		echo "##### -DO -DE referral"
		cleandig foo.$dt.$s.deleg.com A showedns
		echo "##### -DO -DE direct DELEG query"
		cleandig $dt.$s.deleg.com DELEG showedns
		echo "##### -DO -DE direct A query"
		cleandig $dt.$s.deleg.com A showedns
		echo "##### -DO +DE referral"
		cleandig foo.$dt.$s.deleg.com A delegation-extensions showedns
		echo "##### -DO +DE direct DELEG query"
		cleandig $dt.$s.deleg.com DELEG delegation-extensions showedns
		echo "##### -DO +DE direct A query"
		cleandig $dt.$s.deleg.com A delegation-extensions showedns
		echo "##### +DO -DE referral"
		cleandig foo.$dt.$s.deleg.com A dnssec showedns
		echo "##### +DO -DE direct DELEG query"
		cleandig $dt.$s.deleg.com DELEG dnssec showedns
		echo "##### +DO -DE direct A query"
		cleandig $dt.$s.deleg.com A dnssec showedns
		echo "##### +DO +DE referral"
		cleandig foo.$dt.$s.deleg.com A dnssec delegation-extensions showedns
		echo "##### +DO +DE direct DELEG query"
		cleandig $dt.$s.deleg.com DELEG dnssec delegation-extensions showedns
		echo "##### +DO +DE direct A query"
		cleandig $dt.$s.deleg.com A dnssec delegation-extensions showedns
		echo ""
	done
done

echo "### Testing auto DelegInfos"

for s in auto auto-address auto-address-with-aaaa; do
	echo "### Testing $s"
	echo "##### -DE referral"
	cleandig foo.$s.deleg.com A showedns
	echo "##### -DE direct DELEG query"
	cleandig $s.deleg.com DELEG showedns
	echo "##### -DE direct A query"
	cleandig $s.deleg.com A showedns
	echo "##### +DE referral"
	cleandig foo.$s.deleg.com A delegation-extensions showedns
	echo "##### +DE direct DELEG query"
	cleandig $s.deleg.com DELEG delegation-extensions showedns
	echo "##### +DE direct A query"
	cleandig $s.deleg.com A delegation-extensions showedns
	echo ""
done
